# Generated by Django 5.2.4 on 2025-07-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=500)),
                ('avatar', models.ImageField(upload_to='teachers/avatars')),
                ('lesson_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(choices=[('lesson', 'course')], max_length=20)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.teacher')),
            ],
        ),
    ]
