# Generated by Django 5.2.4 on 2025-07-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_teacher_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='student',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
